version: '3.1'

services:
  web:
    build: ./webapp
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hive


