version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./database/sql/hive.sql:/docker-entrypoint-initdb.d/hive.sql
      - data:/var/lib/mysql


volumes:
  data:
